# Generated by Django 3.0.5 on 2020-04-18 22:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=511)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=13)),
                ('release_date', models.DateField()),
                ('abstract_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_books', to='api.AbstractBook')),
            ],
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('currently_reading', models.ManyToManyField(blank=True, related_name='current_readers', to='api.AbstractBook')),
                ('favorite_books', models.ManyToManyField(blank=True, related_name='bookLiker', to='api.AbstractBook')),
                ('followers', models.ManyToManyField(blank=True, related_name='followings', to='api.UserProfile')),
                ('library', models.ManyToManyField(blank=True, related_name='owner', to='api.AbstractBook')),
                ('liked_lists', models.ManyToManyField(blank=True, related_name='listLiker', to='api.BookList')),
                ('my_books', models.ManyToManyField(blank=True, related_name='reader', to='api.AbstractBook')),
                ('read_list', models.ManyToManyField(blank=True, related_name='wisher', to='api.AbstractBook')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.userprofile',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1023)),
                ('abstract_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.AbstractBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'abstract_book')},
                'index_together': {('user', 'abstract_book')},
            },
        ),
        migrations.AddField(
            model_name='booklist',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_lists', to='api.UserProfile'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, max_length=511)),
                ('followers', models.ManyToManyField(blank=True, to='api.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='abstractbook',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.Author'),
        ),
        migrations.AddField(
            model_name='abstractbook',
            name='book_lists',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.BookList'),
        ),
        migrations.CreateModel(
            name='UpDownRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.Book')),
                ('bookList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.BookList')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'bookList'), ('user', 'review'), ('user', 'book')},
                'index_together': {('user', 'bookList'), ('user', 'review'), ('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.AbstractBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile')),
            ],
            options={
                'unique_together': {('user', 'book')},
                'index_together': {('user', 'book')},
            },
        ),
    ]
