# Generated by Django 3.0.5 on 2020-07-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbook',
            name='pop_child_book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pop_of_parent', to='api.Book'),
        ),
    ]
