# Generated by Django 3.0.5 on 2020-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
