# Generated by Django 3.0.5 on 2020-07-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_spoiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='spoiler',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('booklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.BookList')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.UserProfileAPI')),
            ],
            options={
                'unique_together': {('user', 'review'), ('user', 'booklist')},
                'index_together': {('user', 'review'), ('user', 'booklist')},
            },
        ),
    ]
