# Generated by Django 3.0.5 on 2020-07-25 05:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200724_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SPO', 'Spoiler'), ('INV', 'Invective'), ('VIO', 'Violence'), ('OTH', 'Other')], max_length=3)),
                ('text', models.TextField(blank=True, max_length=511, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='api.Comment')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='api.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='api.UserProfileAPI')),
            ],
            options={
                'unique_together': {('user', 'comment'), ('user', 'review')},
                'index_together': {('user', 'comment'), ('user', 'review')},
            },
        ),
    ]
