# Generated by Django 3.0.5 on 2020-07-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200725_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='api.Review'),
        ),
    ]
