# Generated by Django 3.0.5 on 2020-07-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200725_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='complaint',
            index_together=set(),
        ),
    ]
